// Code generated by "stringer -type=Kind -linecomment"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Internal-1]
	_ = x[BadInput-2]
	_ = x[NotFound-3]
	_ = x[AlreadyExists-4]
	_ = x[FailedPrecondition-5]
	_ = x[Unauthorized-6]
	_ = x[Forbidden-7]
}

const _Kind_name = "unknowninternalbad_inputnot_foundalready_existsfailed_preconditionunauthorizedforbidden"

var _Kind_index = [...]uint8{0, 7, 15, 24, 33, 47, 66, 78, 87}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
